apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webapp
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: hello
        image: "famedocker/tryout:latest"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
