apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: go-webapp
    namespace: argocd
spec:
    project: default
    source:
    repoURL: 'this repo url'
    path: overlays
    targetRevision: main
    destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
    syncPolicy:
    automated:
        selfHeal: true
        prune: true